#!/usr/bin/python
import os
import requests
# import pika


print('hello world')
name = os.environ['test-string']
print(f'hello {name}')



# result_dict = {}
# result_dict['success'] = True
# result_dict['container'] = os.uname()[1]
# result_dict['register'] = {}
# result_dict['register']['test2'] = 'successfully register info'

# requests.post(
#     url=os.environ['RESULTS_HOOK'],
#     json=result_dict
# )


# channel.basic_publish(
#     exchange=os.environ['RESULTS_EXCHANGE'], 
#     routing_key=os.environ['RESULTS_QUEUE'],  
#     body=json.dumps(result_dict)
# )
